services:
  cms.backend:
    image: cms.backend
    build:
      context: .
      dockerfile: src/CMS.Backend/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development